### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yehudah** [ulrichwisser/edns#1]
Hi,
Thank you for the package.
I'm running go-lang v1.10 on Ubuntu 16.04 and each run I get this:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5f4312]
goroutine 1 [running]:
main.Test7(0xc42013a6c0, 0x14, 0xc420098250, 0xc, 0x14, 0xc420170370)
/home/user/Downloads/edns-master/edns.go:477 +0x162
main.main()
/home/user/Downloads/edns-master/edns.go:49 +0x637
exit status 2`

**Comment by ulrichwisser** [comment]
Please run the command with the -v flag set. Could you provide the domain name you are testing? It would help the debugging.

**Comment by yehudah** [comment]
Nothing different, I think I'm doing something wrong.
I'm not so familiar with go lang environment.

`go run edns.go ns1.digitalocean.com postmansmtp.com`

**Comment by ulrichwisser** [comment]
Yes, there was a check missing. I just pushed a new version. Please give it a try.

**Comment by yehudah** [comment]
### **I have edited my comment** 

Worked perfectly.

I'm a bit confused, I have a domain that has 'Test1' marked as success and all others failed.
If I run the same domain in the official edns check tool ([link](https://ednscomp.isc.org/ednscomp)), he gets an 'All Ok' status.

How I can determine with your tool if the final result is success or failure for edns support?

**Comment by ulrichwisser** [comment]
Could you please let me know the domain name? 
My test domains do get the same result as the ISC tool.
I would be more than happy to investigate what is going on.
